apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linux-agent
  name: linux-agent-deployment
  namespace: pipelines
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: linux-agent
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: linux-agent
    spec:
      serviceAccountName: sa-aws-azp-pipelineagent
      containers:
        - name: linux-agent
          image: 999999999999.dkr.ecr.us-east-2.amazonaws.com/mgmt/linux-agent:20210304
          imagePullPolicy: IfNotPresent
          env:
            - name: AZP_URL
              value: https://dev.azure.com/Company
            - name: AZP_POOL
              value: EKS-Linux
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azure-devops
                  key: agent-token
            - name: DOCKER_HOST 
              value: tcp://localhost:2375
        - name: docker-daemon
          image: 999999999999.dkr.ecr.us-east-2.amazonaws.com/mgmt/docker-daemon:19.03.14
          imagePullPolicy: IfNotPresent
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          securityContext:
              privileged: true
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: docker-graph-storage
          emptyDir: {}
